### ISSUE TITLE
Got undefined when source and/or target are unknown

### ISSUE THREAD

**Issue by palashmon** [YazilimMuhendisiyizBiz/convert.js#12]
Got undefined when source and/or target are unknown for cases like:

```
convert.DataUnits(1, "mb2", "kb2");
convert.DataUnits(1, "mb2", "kb");
convert.DataUnits(1, "mb", "kb2");
```

I think we can return false in these cases too like we do it for:

`convert.DataUnits("string", "gb", "pb");`

Thanks!

**Comment by ertugrulungor** [comment]
@palashmon  Thank you for the suggestion 👍

**Comment by palashmon** [comment]
Glad to help!
