### ISSUE TITLE
Bitcoin-Para Birimi Dönüştürme

### ISSUE THREAD

**Issue by EraslanAhmet** [YazilimMuhendisiyizBiz/convert.js#32]
**Bitcoin** para biriminin çevirmek istediğimiz para birimlerindeki karşılığını belirleyelim.

**Örneğin:**
```
1 btc = 827.13 $
btc= bitcoin
$= dolar 
```
----------

**Comment by ertugrulungor** [comment]
Bu işin yapılması için kodun bir siteye bağımlı olarak yaşaması gerekiyor. İleride düşünülebilir fakat şu an gerçekleştirmemiz mümkün değil.
