### ISSUE TITLE
ObjectToArray metodunun jQuery bağımlılığı

### ISSUE THREAD

**Issue by cevherkarakoc** [YazilimMuhendisiyizBiz/convert.js#77]
`convert.ObjectToArray("hello, world", ",")` bunu çalıştırdığımda
`Object doesn't support property or method 'trim'` bu çıktıyı alıyorum.
Sebebi ise $.trim()'in kullanılması. Bu metod jQuery ile gelen bir metod. Native olarak trim() var.

**Comment by ertugrulungor** [comment]
Teşekkür ederiz @cevherkarakoc :)
