### ISSUE TITLE
Uncaught TypeError: convert.metric is not a function

### ISSUE THREAD

**Issue by palashmon** [YazilimMuhendisiyizBiz/convert.js#9]
I got an error like

> Uncaught TypeError: convert.metric is not a function

when I executed

`convert.metric(1, "cm", "m");`

in js console, as it is mentioned in the **readme.md**. It worked fine when I used this instead.

`convert.Metric(1, "cm", "m");  // 0.01`

I think you just need to update the **readme.md** file. 

Thanks!

**Comment by yakupad** [comment]
Thanks. 
Update Readme.md convert.metric --> convert.Metric 
https://github.com/YazilimMuhendisiyizBiz/convert.js/commit/5088aba2bbaf28754538a25e1c920a552f430248
